version: '3.8'

services:
  kb-frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      # 应用配置 - 这些可以在运行时通过挂载的.env.local覆盖
      - NEXT_PUBLIC_APP_ID=${NEXT_PUBLIC_APP_ID:-}
      - NEXT_PUBLIC_APP_KEY=${NEXT_PUBLIC_APP_KEY:-}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-}
      - NEXT_PUBLIC_CAS_BASE_URL=${NEXT_PUBLIC_CAS_BASE_URL:-http://192.168.50.178:8443/cas}
      - NEXT_PUBLIC_CAS_SERVICE_URL=${NEXT_PUBLIC_CAS_SERVICE_URL:-http://192.168.50.70:3000/login}
      
      # CAS服务器端配置
      - CAS_BASE_URL=${CAS_BASE_URL:-http://192.168.50.178:8443/cas}
      - CAS_SERVICE_URL=${CAS_SERVICE_URL:-http://192.168.50.70:3000/login}
      
      # NextAuth配置
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://192.168.50.70:3000}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-change-me-in-production}
      
      # 环境设置
      - NODE_ENV=${NODE_ENV:-development}
      
      # HTTPS设置 - 设置为true启用HTTPS和自签证书
      - HTTPS=${HTTPS:-false}
      - SSL_DOMAIN=${SSL_DOMAIN:-localhost}
      
    volumes:
      # 挂载.env.local文件，实现运行时配置更新
      - ./.env.local:/app/.env.local:ro
      
      # 可选：挂载自定义TLS证书（如果不挂载将自动生成自签证书）
      # - ./certs/server.crt:/app/certs/server.crt:ro
      # - ./certs/server.key:/app/certs/server.key:ro
      
      # 可选：持久化日志
      # - ./logs:/app/logs
      
    restart: unless-stopped
    
    # 健康检查
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "http://localhost:3000/api/config"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# 可选：添加nginx反向代理支持HTTPS终止
# 取消注释以下部分如果您希望nginx处理TLS
# 
#   nginx:
#     image: nginx:alpine
#     ports:
#       - "80:80"
#       - "443:443"
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf:ro
#       - ./certs:/etc/nginx/certs:ro
#     depends_on:
#       - kb-frontend
#     restart: unless-stopped