name: Build Docker Image for Release

on:
  # 只在创建release时触发
  release:
    types: [published]
  
  # 手动触发（用于测试）
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build production image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: kb-frontend:${{ github.event.release.tag_name || 'latest' }}
        outputs: type=docker,dest=/tmp/kb-frontend.tar
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Upload Docker image to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: /tmp/kb-frontend.tar
        asset_name: kb-frontend-${{ github.event.release.tag_name }}.tar
        asset_content_type: application/x-tar